"""empty message

Revision ID: 280e8c6eb356
Revises: 7f24d24d6854
Create Date: 2025-06-24 22:15:13.024328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280e8c6eb356'
down_revision = '7f24d24d6854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.alter_column('console_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('renter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.alter_column('renter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('console_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
