"""empty message

Revision ID: 7f24d24d6854
Revises: 08c3024ab7ff
Create Date: 2025-06-19 10:34:25.341284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f24d24d6854'
down_revision = '08c3024ab7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.drop_column('zip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
