"""empty message

Revision ID: 98f3d8e0d66a
Revises: 280e8c6eb356
Create Date: 2025-08-08 15:23:12.066530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f3d8e0d66a'
down_revision = '280e8c6eb356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
